# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=250)),
                ('family_location', models.CharField(max_length=250)),
                ('family_logo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('second_name', models.CharField(max_length=250)),
                ('person_photo', models.FileField(upload_to='')),
                ('date_of_birth', models.CharField(max_length=100)),
                ('date_of_death', models.CharField(max_length=100)),
                ('is_married', models.BooleanField(default=False)),
                ('lives_in', models.CharField(max_length=100)),
                ('person_descr', models.CharField(max_length=500)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Family')),
            ],
        ),
    ]
