# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_auto_20160908_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='family_id',
            new_name='family',
        ),
    ]
