# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_person_is_merried'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='is_merried',
            new_name='is_married',
        ),
    ]
