# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0006_auto_20160909_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_logo',
            field=models.ImageField(upload_to='families'),
        ),
    ]
