# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0007_auto_20160920_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_logo',
            field=models.ImageField(upload_to='family_logo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_photo',
            field=models.ImageField(upload_to='person_photo'),
        ),
    ]
