# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0008_auto_20160920_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_logo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_photo',
            field=models.FileField(upload_to=''),
        ),
    ]
