# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0010_auto_20160921_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='person_date_birth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='person_date_death',
            new_name='date_of_death',
        ),
    ]
