# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0011_auto_20160921_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='lives_in',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
