# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0012_person_lives_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_descr',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
