# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0013_person_person_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_death',
            field=models.DateField(verbose_name='death date'),
        ),
    ]
