# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0014_auto_20161129_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_death',
            field=models.CharField(max_length=100),
        ),
    ]
